[project]
name = "streamlit-app"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.3",
    "pandas>=2.3.3",
    "streamlit>=1.52.2",
]
